In [1]:
import numpy as np
import tensorflow as tf

In [2]:
file = np.load('Divorce_data_train.npz')
train_inputs_tf , train_targets_tf = file['inputs'].astype(float),file['targets'].astype(int)

file = np.load('Divorce_data_validation.npz')
validation_inputs_tf , validation_targets_tf = file['inputs'].astype(float),file['targets'].astype(int)

file = np.load('Divorce_data_test.npz')
test_inputs_tf , test_targets_tf = file['inputs'].astype(float),file['targets'].astype(int)
#print(train_inputs_tf)
print(train_inputs_tf.shape)
print(validation_inputs_tf.shape)
print(train_targets_tf.shape)
print(validation_targets_tf.shape)
print(train_inputs_tf)

(136, 54)
(17, 54)
(136,)
(17,)
[[2. 2. 4. ... 3. 2. 1.]
 [4. 4. 4. ... 4. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [1. 2. 0. ... 2. 1. 0.]
 [1. 0. 1. ... 3. 2. 2.]
 [0. 0. 0. ... 3. 1. 1.]]


In [11]:
#model
from keras import regularizers
input_size = 54
output_size = 2
hidden_layer_size = 100


model = tf.keras.Sequential([
                            tf.keras.layers.Dense(hidden_layer_size,activation = 'relu'),
                            tf.keras.layers.Dense(hidden_layer_size,activation = 'relu'),
                            tf.keras.layers.Dense(hidden_layer_size,activation = 'relu'),
                            tf.keras.layers.Dense(hidden_layer_size,activation = 'relu'),
                            tf.keras.layers.Dense(hidden_layer_size,activation = 'relu'),
                            tf.keras.layers.Dense(hidden_layer_size,activation = 'relu'),
                            tf.keras.layers.Dense(output_size,activation = 'softmax')
                            ])

model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy',metrics = ['accuracy'])
batch_size = 10
max_epochs = 4
early_stopping = tf.keras.callbacks.EarlyStopping(patience=2)


model.fit(train_inputs_tf,
          train_targets_tf,
          batch_size = batch_size,
          epochs = max_epochs,
          callbacks = [early_stopping],
          validation_data = (validation_inputs_tf , validation_targets_tf),
          verbose = 2)

Epoch 1/4
14/14 - 0s - loss: 0.4005 - accuracy: 0.6912 - val_loss: 0.3236 - val_accuracy: 1.0000 - 454ms/epoch - 32ms/step
Epoch 2/4
14/14 - 0s - loss: 0.0953 - accuracy: 0.9779 - val_loss: 0.0356 - val_accuracy: 1.0000 - 38ms/epoch - 3ms/step
Epoch 3/4
14/14 - 0s - loss: 0.0199 - accuracy: 1.0000 - val_loss: 0.0851 - val_accuracy: 0.9412 - 37ms/epoch - 3ms/step
Epoch 4/4
14/14 - 0s - loss: 0.0012 - accuracy: 1.0000 - val_loss: 0.0046 - val_accuracy: 1.0000 - 32ms/epoch - 2ms/step


In [12]:
test_loss, test_accuracy = model.evaluate(test_inputs_tf, test_targets_tf)

1/1 [==============================] - 0s 14ms/step - loss: 0.0250 - accuracy: 1.0000


In [13]:
print('\nTest loss: {0:.2f}. Test accuracy: {1:.2f}%'.format(test_loss, test_accuracy*100.))


Test loss: 0.03. Test accuracy: 100.00%
